---
- hosts: l2sw
  gather_facts: no
  connection: local

  tasks:
    - name: show
      ios_command:
        authorize: yes
        commands:
          - show run
        provider:
          username: isd_nw
          password: fantasti9
          auth_pass: fantasti9
      register: result

    - name: debug
      debug:
        msg: "{{ result.stdout_lines[0] }}"
