---
- hosts: switch
  gather_facts: no
  connection: local

  tasks:
    - name: crawl config file
      local_action:
        module: ios_command
        authorize: yes
        autho_pass: "{{ enable_pass }}"
        username: "{{ ansible_ssh_user }}"
        password: "{{ ansible_ssh_pass }}"
        host: "{{ inventory_hostname }}"
        commands:
          - show run
      register: result
